var configMongo = {};

configMongo.mongoHost = '127.0.0.1';
configMongo.mongoPort = 27017;

configMongo.company_code = 'newco';
configMongo.output_to_folder_only = 'n';
configMongo.input_folder = 'mongo_english';
configMongo.output_folder = 'mongo_english_out';
configMongo.import_already_rendered_to_mongo = 'n';

/////////////////////////////////////////////////////////////////
configMongo.new_or_existing_customer 	= 'y';

configMongo.product_installation 		= 'MobileEcommerce';
configMongo.product2_installation 		= 'Mobileticket';
configMongo.product3_installation 		= 'MobileticketBulk';
configMongo.product4_installation 		= 'jobsite';

configMongo.product_default_option		= 'y';

configMongo.customer_code 				= 'newco';
configMongo.customer_name 				= 'New Company Inc.';
configMongo.customer_timezone 			= '-0500';
configMongo.customer_observer_dst 		= 'y';
configMongo.customer_notification_email = 'newco@gmail.com';
configMongo.customer_color_scheme 		= '#B2A876';
configMongo.customer_color_scheme_secondary = '#B2A876';
configMongo.logo_upload 				= 'y';

configMongo.customer_MOBILEcommerce 	= 'MobileEcommerce';
configMongo.customer_MOBILEticket	 	= 'Mobileticket';
configMongo.customer_MOBILEticket_for_bulk 	= 'mobileticketbulk';

configMongo.end_point = 'localhost';
configMongo.end_point_port = '3000';
configMongo.adv_order_req = 'n';
configMongo.edx_gateway_ip = 'http://201.234.199.99';
configMongo.edx_gateway_port = '35243';
configMongo.reorder_request_mail = 'abc@abc.com';
configMongo.on_base = 'y';
configMongo.provider_url = 'abc@abc.com';

configMongo.commerceversion = '1.3';

configMongo.product1_install = 'y';
configMongo.product2_install = 'y';
configMongo.product3_install = 'y';
configMongo.product4_install = 'y';

/////////////////////////////////////////////////////////////////

//sections
configMongo.templateDefinitions_order = 'y';
configMongo.templateDefinitions_order_sms = 'y';
configMongo.templateDefinitions_ticket = 'y';
configMongo.templateDefinitions_ticket_sms = 'y';
configMongo.templateDefinitions_reorder = 'y';
configMongo.templateDefinitions_future_order = 'y';

configMongo.productDefinitions_commerce = 'y';
configMongo.productDefinitions_ticket = 'y';
configMongo.productDefinitions_jobsite = 'y';
configMongo.productDefinitions_supply = 'y';
configMongo.productDefinitions_evoadmin = 'y';

configMongo.notificationDefinitions_order_create = 'y';
configMongo.notificationDefinitions_ticket_create = 'y';

configMongo.Users_products_commerce = 'y';
configMongo.Users_products_ticket = 'y';
configMongo.Users_products_jobsite = 'y';
configMongo.Users_products_evoadmin = 'y';

configMongo.Companies_products_commerce = 'y';
configMongo.Companies_products_ticket = 'y';
configMongo.Companies_products_jobsite = 'y';
configMongo.Companies_products_supply = 'y';
configMongo.Companies_products_evoadmin = 'y';

configMongo.templateDefinitions_order_company = "concrite";
configMongo.templateDefinitions_order_name = "Order";
configMongo.templateDefinitions_order_transport_type = "email";
configMongo.templateDefinitions_order_transport_name = "Email";
configMongo.templateDefinitions_order_transport_grouped = true;
configMongo.templateDefinitions_order_bod_name = "Order";
configMongo.templateDefinitions_order_formatter = "jade";
configMongo.templateDefinitions_order_subject_type = "text";
configMongo.templateDefinitions_order_subject_value = "|Order: #{Order.customer.order.code} #{moment(Order.customer.order.startTime).format('ll')}";
configMongo.templateDefinitions_order_content_type = "file";
configMongo.templateDefinitions_order_content_value = "/opt/cai/evolution/assets/concrite/templates/order.jade";
configMongo.templateDefinitions_order_content_attachments_fileName = "";
configMongo.templateDefinitions_order_content_attachments_filePath = "/opt/cai/evolution/assets/concrite/img/concrite.png";
configMongo.templateDefinitions_order_content_attachments_cid = "concrite.png";
configMongo.templateDefinitions_order_active = true;

configMongo.templateDefinitions_order_sms_company = "concrite";
configMongo.templateDefinitions_order_sms_name = "Order SMS";
configMongo.templateDefinitions_order_sms_transport_type = "sms";
configMongo.templateDefinitions_order_sms_transport_name = "SMS";
configMongo.templateDefinitions_order_sms_transport_grouped = false;
configMongo.templateDefinitions_order_sms_bod_name = "Order";
configMongo.templateDefinitions_order_sms_formatter = "jade";
configMongo.templateDefinitions_order_sms_subject_type = "text";
configMongo.templateDefinitions_order_sms_subject_value = "";
configMongo.templateDefinitions_order_sms_content_type = "file";
configMongo.templateDefinitions_order_sms_content_value = "/opt/cai/evolution/assets/concrite/templates/order.sms.jade";
configMongo.templateDefinitions_order_sms_active = true;

configMongo.templateDefinitions_ticket_company = "concrite";
configMongo.templateDefinitions_ticket_name = "Ticket";
configMongo.templateDefinitions_ticket_transport_type = "email";
configMongo.templateDefinitions_ticket_transport_name = "Email";
configMongo.templateDefinitions_ticket_transport_grouped = true;
configMongo.templateDefinitions_ticket_bod_name = "Ticket";
configMongo.templateDefinitions_ticket_formatter = "jade";
configMongo.templateDefinitions_ticket_subject_type = "text";
configMongo.templateDefinitions_ticket_subject_value = "|Ticket: #{Ticket.customer.order.ticket.ticketNum}, for Order #{Ticket.customer.order.code}, #{moment(Ticket.customer.order.startTime).format('ll')} has been shipped";
configMongo.templateDefinitions_ticket_content_type = "file";
configMongo.templateDefinitions_ticket_content_value = "/opt/cai/evolution/assets/concrite/templates/ticket.jade";
configMongo.templateDefinitions_ticket_content_attachments_fileName = "";
configMongo.templateDefinitions_ticket_content_attachments_filePath = "/opt/cai/evolution/assets/concrite/img/concrite.png";
configMongo.templateDefinitions_ticket_content_attachments_cid = "concrite.png";
configMongo.templateDefinitions_ticket_active = true;

configMongo.templateDefinitions_ticket_sms_company = "concrite";
configMongo.templateDefinitions_ticket_sms_name = "Ticket SMS";
configMongo.templateDefinitions_ticket_sms_transport_type = "sms";
configMongo.templateDefinitions_ticket_sms_transport_name = "SMS";
configMongo.templateDefinitions_ticket_sms_transport_grouped = false;
configMongo.templateDefinitions_ticket_sms_bod_name = "Ticket";
configMongo.templateDefinitions_ticket_sms_formatter = "jade";
configMongo.templateDefinitions_ticket_sms_subject_type = "text";
configMongo.templateDefinitions_ticket_sms_subject_value = "";
configMongo.templateDefinitions_ticket_sms_content_type = "file";
configMongo.templateDefinitions_ticket_sms_content_value = "/opt/cai/evolution/assets/concrite/templates/ticket.sms.jade";
configMongo.templateDefinitions_ticket_sms_active = true;

configMongo.templateDefinitions_reorder_company = "concrite";
configMongo.templateDefinitions_reorder_name = "Order Request";
configMongo.templateDefinitions_reorder_transport_type = "email";
configMongo.templateDefinitions_reorder_transport_name = "Email";
configMongo.templateDefinitions_reorder_transport_grouped = true;
configMongo.templateDefinitions_reorder_bod_name = "OrderRequest";
configMongo.templateDefinitions_reorder_formatter = "jade";
configMongo.templateDefinitions_reorder_subject_type = "text";
configMongo.templateDefinitions_reorder_subject_value = "|Reorder Request: !{customer.name} for #{moment(concrete.startDate).format('ll')}";
configMongo.templateDefinitions_reorder_content_type = "file";
configMongo.templateDefinitions_reorder_content_value = "/opt/cai/evolution/assets/concrite/templates/reorder.jade";
configMongo.templateDefinitions_reorder_content_attachments_fileName = "";
configMongo.templateDefinitions_reorder_content_attachments_filePath = "/opt/cai/evolution/assets/concrite/img/concrite.png";
configMongo.templateDefinitions_reorder_content_attachments_cid = "concrite.png";
configMongo.templateDefinitions_reorder_active = true;

configMongo.templateDefinitions_future_order_company = "concrite";
configMongo.templateDefinitions_future_order_name = "Future Order";
configMongo.templateDefinitions_future_order_transport_type = "email";
configMongo.templateDefinitions_future_order_transport_name = "Email";
configMongo.templateDefinitions_future_order_transport_grouped = true;
configMongo.templateDefinitions_future_order_bod_name = "OrderRequest";
configMongo.templateDefinitions_future_order_formatter = "jade";
configMongo.templateDefinitions_future_order_subject_type = "text";
configMongo.templateDefinitions_future_order_subject_value = "|Upcoming Orders";
configMongo.templateDefinitions_future_order_content_type = "file";
configMongo.templateDefinitions_future_order_content_value = "/opt/cai/evolution/assets/concrite/templates/futureOrders.jade";
configMongo.templateDefinitions_future_order_content_attachments_fileName = "";
configMongo.templateDefinitions_future_order_content_attachments_filePath = "/opt/cai/evolution/assets/concrite/img/concrite.png";
configMongo.templateDefinitions_future_order_content_attachments_cid = "concrite.png";
configMongo.templateDefinitions_future_order_active = true;

configMongo.productDefinitions_commerce_code = "commerce";
configMongo.productDefinitions_commerce_name = "MOBILEcommerce";
configMongo.productDefinitions_commerce_description = "MOBILEcommerce";
configMongo.productDefinitions_commerce_roles = "globaladmin";
configMongo.productDefinitions_commerce_roles2 = "appadmin";
configMongo.productDefinitions_commerce_roles3 = "appuser";
configMongo.productDefinitions_commerce_platforms_desktop = "desktop";
configMongo.productDefinitions_commerce_platforms_mobile = "mobile";
configMongo.productDefinitions_commerce_platforms_tablet = "desktop";
configMongo.productDefinitions_commerce_settings = "";

configMongo.productDefinitions_ticket_code = "ticket";
configMongo.productDefinitions_ticket_name = "MOBILEticket";
configMongo.productDefinitions_ticket_description = "MOBILEticket";
configMongo.productDefinitions_ticket_roles = "globaladmin";
configMongo.productDefinitions_ticket_roles2 = "appadmin";
configMongo.productDefinitions_ticket_roles3 = "appuser";
configMongo.productDefinitions_ticket_platforms_desktop = "desktop";
configMongo.productDefinitions_ticket_platforms_mobile = "desktop";
configMongo.productDefinitions_ticket_platforms_tablet = "desktop";
configMongo.productDefinitions_ticket_settings = "";

configMongo.productDefinitions_bulkticket_code = "MobileticketBulk";
configMongo.productDefinitions_bulkticket_name = "MobileticketBulk";
configMongo.productDefinitions_bulkticket_description = "MobileticketBulk";
configMongo.productDefinitions_bulkticket_roles = "globaladmin";
configMongo.productDefinitions_bulkticket_roles2 = "appadmin";
configMongo.productDefinitions_bulkticket_roles3 = "appuser";
configMongo.productDefinitions_bulkticket_platforms_desktop = "desktop";
configMongo.productDefinitions_bulkticket_platforms_mobile = "desktop";
configMongo.productDefinitions_bulkticket_platforms_tablet = "desktop";
configMongo.productDefinitions_bulkticket_settings = "";

configMongo.productDefinitions_jobsite_code = "jobsite";
configMongo.productDefinitions_jobsite_name = "MOBILEjobsite";
configMongo.productDefinitions_jobsite_description = "MOBILEjobsite";
configMongo.productDefinitions_jobsite_roles = "globaladmin";
configMongo.productDefinitions_jobsite_roles2 = "appadmin";
configMongo.productDefinitions_jobsite_roles3 = "appuser";
configMongo.productDefinitions_jobsite_roles4 = "ionicadmin";
configMongo.productDefinitions_jobsite_platforms_desktop = "mobile";
configMongo.productDefinitions_jobsite_platforms_mobile = "mobile";
configMongo.productDefinitions_jobsite_platforms_tablet = "mobile";
configMongo.productDefinitions_jobsite_settings = "";

configMongo.productDefinitions_supply_code = "supply";
configMongo.productDefinitions_supply_name = "supplyCONNECT";
configMongo.productDefinitions_supply_description = "supplyCONNECT";
configMongo.productDefinitions_supply_roles_code = "appAdmin";
configMongo.productDefinitions_supply_roles_name = "Application Admin";
configMongo.productDefinitions_supply_roles_category = "";
configMongo.productDefinitions_supply_roles_code2 = "locationadmin";
configMongo.productDefinitions_supply_roles_name2 = "Locations Admin";
configMongo.productDefinitions_supply_roles_category2 = "";
configMongo.productDefinitions_supply_roles_code3 = "vendoradmin";
configMongo.productDefinitions_supply_roles_name3 = "Vendors Admin";
configMongo.productDefinitions_supply_roles_category3 = "";
configMongo.productDefinitions_supply_roles_code4 = "materialmgr";
configMongo.productDefinitions_supply_roles_name4 = "Material Manager";
configMongo.productDefinitions_supply_roles_category4 = "users";
configMongo.productDefinitions_supply_roles_code5 = "plantmgr";
configMongo.productDefinitions_supply_roles_name5 = "Plant Manager";
configMongo.productDefinitions_supply_roles_category5 = "users";
configMongo.productDefinitions_supply_roles_code6 = "vendor";
configMongo.productDefinitions_supply_roles_name6 = "Vendor";
configMongo.productDefinitions_supply_roles_category6 = "users";
configMongo.productDefinitions_supply_platforms_desktop = "desktop";
configMongo.productDefinitions_supply_settings_vendor = "";
configMongo.productDefinitions_supply_settings_permissions_configure = false;
configMongo.productDefinitions_supply_settings_permissions_plan = false;
configMongo.productDefinitions_supply_settings_permissions_alias = false;
configMongo.productDefinitions_supply_settings_locations = "";
configMongo.productDefinitions_supply_appAdmin = true;

configMongo.productDefinitions_evoadmin_code = "evoadmin";
configMongo.productDefinitions_evoadmin_name = "EVOAdmin";
configMongo.productDefinitions_evoadmin_description = "EVOAdmin";
configMongo.productDefinitions_evoadmin_roles = "caadmin";
configMongo.productDefinitions_evoadmin_roles2 = "companyadmin";
configMongo.productDefinitions_evoadmin_platforms_desktop = "desktop";
configMongo.productDefinitions_evoadmin_platforms_mobile = "mobile";
configMongo.productDefinitions_evoadmin_platforms_tablet = "desktop";
configMongo.productDefinitions_evoadmin_settings = "";

configMongo.notificationDefinitions_order_create_company = "concrite";
configMongo.notificationDefinitions_order_create_name = "Order Create";
configMongo.notificationDefinitions_order_create_bod_name = "Order";
configMongo.notificationDefinitions_order_create_bod_filterDefinitions_name = "Customer";
configMongo.notificationDefinitions_order_create_bod_filterDefinitions_type = "JPATH";
configMongo.notificationDefinitions_order_create_bod_filterDefinitions_expression = "customer.code";
configMongo.notificationDefinitions_order_create_bod_filterDefinitions_name2 = "Project";
configMongo.notificationDefinitions_order_create_bod_filterDefinitions_type2 = "JPATH";
configMongo.notificationDefinitions_order_create_bod_filterDefinitions_expression2 = "customer.order.projectCode";
configMongo.notificationDefinitions_order_create_bod_contextDefinitions = "";
configMongo.notificationDefinitions_order_create_context = "Customer";
configMongo.notificationDefinitions_order_create_context2 = "Project";
configMongo.notificationDefinitions_order_create_context3 = "Order";
configMongo.notificationDefinitions_order_create_transports_type = "email";
configMongo.notificationDefinitions_order_create_transports_name = "Email";
configMongo.notificationDefinitions_order_create_transports_grouped = true;
configMongo.notificationDefinitions_order_create_transports_template_name = "Order";
configMongo.notificationDefinitions_order_create_transports_type2 = "sms";
configMongo.notificationDefinitions_order_create_transports_name2 = "SMS";
configMongo.notificationDefinitions_order_create_transports_grouped2 = false;
configMongo.notificationDefinitions_order_create_transports_template_name2 = "Order SMS";

configMongo.notificationDefinitions_ticket_create_company = "concrite";
configMongo.notificationDefinitions_ticket_create_name = "Ticket Create";
configMongo.notificationDefinitions_ticket_create_bod_name = "Ticket";
configMongo.notificationDefinitions_ticket_create_bod_filterDefinitions_name = "Order ID";
configMongo.notificationDefinitions_ticket_create_bod_filterDefinitions_type = "JPATH";
configMongo.notificationDefinitions_ticket_create_bod_filterDefinitions_expression = "customer.order._id";
configMongo.notificationDefinitions_ticket_create_bod_contextDefinitions = "";
configMongo.notificationDefinitions_ticket_create_context = "Customer";
configMongo.notificationDefinitions_ticket_create_context2 = "Project";
configMongo.notificationDefinitions_ticket_create_context3 = "Order";
configMongo.notificationDefinitions_ticket_create_transports_type = "email";
configMongo.notificationDefinitions_ticket_create_transports_name = "Email";
configMongo.notificationDefinitions_ticket_create_transports_grouped = true;
configMongo.notificationDefinitions_ticket_create_transports_template_name = "Ticket";
configMongo.notificationDefinitions_ticket_create_transports_type2 = "sms";
configMongo.notificationDefinitions_ticket_create_transports_name2 = "SMS";
configMongo.notificationDefinitions_ticket_create_transports_grouped2 = false;
configMongo.notificationDefinitions_ticket_create_transports_template_name2 = "Ticket SMS";

configMongo.Users_userName = "";
configMongo.Users_hash = "";
configMongo.Users_firstName = "";
configMongo.Users_lastName = "";
configMongo.Users_email = "";
configMongo.Users_passwordLifetime = 0;
configMongo.Users_resetPassword = false;
configMongo.Users_loginAttempts = 0;
configMongo.Users_lastLogin = null;
configMongo.Users_lastLogout = null;
configMongo.Users_totalLogins = 0;
configMongo.Users_status = "Active";
configMongo.Users_company = "";
configMongo.Users_type = "Context";

configMongo.Users_products_commerce_code = "commerce";
configMongo.Users_products_commerce_roles = "appadmin";
configMongo.Users_products_commerce_roles2 = "appuser";
configMongo.Users_products_commerce_settings_sms = "";
configMongo.Users_products_commerce_settings_customer_code = "";
configMongo.Users_products_commerce_settings_customer_name = "";
configMongo.Users_products_commerce_settings_sales = "";
configMongo.Users_products_commerce_settings_timeZone_value = "-0500";
configMongo.Users_products_commerce_settings_timeZone_operator = "-";
configMongo.Users_products_commerce_settings_timeZone_hours = "05";
configMongo.Users_products_commerce_settings_timeZone_minutes = "00";
configMongo.Users_products_commerce_settings_permissions_batchWeights = false;
configMongo.Users_products_commerce_settings_permissions_truckTimes = true;
configMongo.Users_products_commerce_settings_permissions_pricing = false;
configMongo.Users_products_commerce_settings_permissions_mapping = true;
configMongo.Users_products_commerce_settings_permissions_acctInfo = false;
configMongo.Users_products_commerce_settings_permissions_docImage = false;
configMongo.Users_products_commerce_settings_permissions_futureOrderEmail = true;
configMongo.Users_products_commerce_settings_permissions_changeCustomer = false;
configMongo.Users_products_commerce_settings_permissions_isAdmin = false;
configMongo.Users_products_commerce_settings_permissions_timeZone = true;
configMongo.Users_products_commerce_settings_permissions_advancedOrderRequest = true;
configMongo.Users_products_commerce_settings_permissions_reports = true;

configMongo.Users_products_ticket_code = "ticket";
configMongo.Users_products_ticket_roles = "appadmin";
configMongo.Users_products_ticket_settings_permissions_isAdmin = true;
configMongo.Users_products_ticket_settings_permissions_legalAdmin = true;

configMongo.Users_products_bulkticket_code = "MobileticketBulk";
configMongo.Users_products_bulkticket_roles = "appadmin";
configMongo.Users_products_bulkticket_settings_permissions_isAdmin = true;
configMongo.Users_products_bulkticket_settings_permissions_legalAdmin = true;

configMongo.Users_products_jobsite_code = "jobsite";
configMongo.Users_products_jobsite_roles = "appadmin";
configMongo.Users_products_jobsite_roles2 = "appuser";
configMongo.Users_products_jobsite_roles3 = "ionicadmin";
configMongo.Users_products_jobsite_settings_sms = "";
configMongo.Users_products_jobsite_settings_customer_code = "";
configMongo.Users_products_jobsite_settings_customer_name = "";
configMongo.Users_products_jobsite_settings_sales = "";
configMongo.Users_products_jobsite_settings_timeZone_value = "-0500";
configMongo.Users_products_jobsite_settings_timeZone_operator = "-";
configMongo.Users_products_jobsite_settings_timeZone_hours = "05";
configMongo.Users_products_jobsite_settings_timeZone_minutes = "00";
configMongo.Users_products_jobsite_settings_permissions_batchWeights = false;
configMongo.Users_products_jobsite_settings_permissions_truckTimes = true;
configMongo.Users_products_jobsite_settings_permissions_pricing = false;
configMongo.Users_products_jobsite_settings_permissions_mapping = true;
configMongo.Users_products_jobsite_settings_permissions_acctInfo = false;
configMongo.Users_products_jobsite_settings_permissions_docImage = false;
configMongo.Users_products_jobsite_settings_permissions_futureOrderEmail = true;
configMongo.Users_products_jobsite_settings_permissions_changeCustomer = false;
configMongo.Users_products_jobsite_settings_permissions_isAdmin = false;
configMongo.Users_products_jobsite_settings_permissions_timeZone = true;
configMongo.Users_products_jobsite_settings_permissions_advancedOrderRequest = true;
configMongo.Users_products_jobsite_settings_permissions_reports = true;

configMongo.Users_products_evoadmin_code = "evoadmin";
configMongo.Users_products_evoadmin_roles = "companyadmin";

configMongo.Companies_code = "newco";
configMongo.Companies_description = "";
configMongo.Companies_status = "y";
configMongo.Companies_settings_communications_email_from_name = "Newco Corp";
configMongo.Companies_settings_communications_email_from_value = "info@newco.com";
configMongo.Companies_settings_cloudStore = 'n';
configMongo.Companies_customBranding_font_2 = "#000000";
configMongo.Companies_customBranding_font = "#FFFFFF";
configMongo.Companies_branding_primary = "@color-primary: #700E31;";
configMongo.primary_branding_text_color = "@color-primary: #700E31;";
configMongo.Companies_branding_secondary = "@color-secondary: #996633 ;";
configMongo.Companies_branding_text_primary = "@text-primary: #00cc00;";
configMongo.Companies_branding_text_secondary = "@text-secondary: #FFFFFF;";
configMongo.Companies_branding_logo = "@logo: 'company-logo.png';";
configMongo.Companies_images_smallLogo = "@logo: 'logo.png';";

configMongo.Companies_products_commerce_code = "commerce";
configMongo.Companies_products_commerce_settings_env = "alpha";
configMongo.Companies_products_commerce_settings_env_prod = "production";
configMongo.Companies_products_commerce_settings_systemType = "integra";
configMongo.Companies_products_commerce_settings_documentsConfig = "";
configMongo.Companies_products_commerce_settings_edxGatewayConfig_ServerAddress = "http://localhost";
configMongo.Companies_products_commerce_settings_edxGatewayConfig_Port = "35244";
configMongo.Companies_products_commerce_settings_dataEndPoints_LegacyDataService_EndPointAddress = "http://localhost";
configMongo.Companies_products_commerce_settings_dataEndPoints_LegacyDataService_Port = 35244;
configMongo.Companies_products_commerce_settings_dataEndPoints_LegacyDataService_Type = "REST";
configMongo.Companies_products_commerce_settings_dataEndPoints_LegacyDataService_SubType = "Client";
configMongo.Companies_products_commerce_settings_dataEndPoints_SocketEndPoint_EndPointAddress = "http://localhost";
configMongo.Companies_products_commerce_settings_dataEndPoints_SocketEndPoint_Port = 35244;
configMongo.Companies_products_commerce_settings_dataEndPoints_SocketEndPoint_Type = "REST";
configMongo.Companies_products_commerce_settings_dataEndPoints_SocketEndPoint_SubType = "Server";
configMongo.Companies_products_commerce_settings_futureOrdersEmail_generateTime = "1127";
configMongo.Companies_products_commerce_settings_futureOrdersEmail_durationTimePeriod = 3;
configMongo.Companies_products_commerce_settings_futureOrdersEmail_template = "Future Order";
configMongo.Companies_products_commerce_settings_notifications_orderRequest_template = "Order Request";
configMongo.Companies_products_commerce_settings_notifications_orderRequest_template_to_name = "";
configMongo.Companies_products_commerce_settings_notifications_orderRequest_template_to_value = "";
configMongo.Companies_products_commerce_settings_notifications_orderCreate_template = "Order Create";
configMongo.Companies_products_commerce_settings_notifications_ticketCreate_template = "Ticket Create";
configMongo.Companies_products_commerce_settings_company_advancedOrderRequest = true;
configMongo.Companies_products_commerce_settings_company_acctInfo = true;
configMongo.Companies_products_commerce_settings_company_docImage = true;
configMongo.Companies_products_commerce_settings_company_timeZone_value = "0600";
configMongo.Companies_products_commerce_settings_company_timeZone_operator = "-";
configMongo.Companies_products_commerce_settings_company_timeZone_hours = "06";
configMongo.Companies_products_commerce_settings_company_timeZone_minutes = "00";
configMongo.Companies_products_commerce_settings_company_timeZone_name = "US/Central";
configMongo.Companies_products_commerce_settings_company_timeZone_defaultRegion = "USA";
configMongo.Companies_products_commerce_settings_user_sms = "";
configMongo.Companies_products_commerce_settings_user_customer_code = "";
configMongo.Companies_products_commerce_settings_user_customer_name = "";
configMongo.Companies_products_commerce_settings_user_sales = "";
configMongo.Companies_products_commerce_settings_user_timeZone_value = "";
configMongo.Companies_products_commerce_settings_user_timeZone_operator = "";
configMongo.Companies_products_commerce_settings_user_timeZone_hours = "";
configMongo.Companies_products_commerce_settings_user_timeZone_minutes = "";
configMongo.Companies_products_commerce_settings_user_permissions_batchWeights = false;
configMongo.Companies_products_commerce_settings_user_permissions_truckTimes = true;
configMongo.Companies_products_commerce_settings_user_permissions_pricing = false;
configMongo.Companies_products_commerce_settings_user_permissions_mapping = true;
configMongo.Companies_products_commerce_settings_user_permissions_acctInfo = false;
configMongo.Companies_products_commerce_settings_user_permissions_docImage = false;
configMongo.Companies_products_commerce_settings_user_permissions_futureOrderEmail = true;
configMongo.Companies_products_commerce_settings_user_permissions_changeCustomer = false;
configMongo.Companies_products_commerce_settings_user_permissions_isAdmin = false;
///////////////////////////////////////////////////////////////////////////////////
configMongo.Companies_products_commerce_settings_documentsConfig_providerAddress = "http://localhost";
configMongo.Companies_products_commerce_settings_documentsConfig_documentsUseChecksum = false;
configMongo.Companies_products_commerce_settings_documentsConfig_documents_ticketUrl = "KT103_0_0_0={ticketCode}&KT102_0_0_0={customerCode}&clienttype=html&cqid=106&filetype=PDF";
configMongo.Companies_products_commerce_settings_documentsConfig_documents_invoiceUrl = "KT106_0_0_0={invoiceNumber}&KT102_0_0_0={customerCode}&clienttype=html&cqid=105&filetype=PDF";
configMongo.Companies_products_commerce_settings_documentsConfig_documents_invoiceByDateUrl = "KT102_0_0_0={customerCode}&ToDate={toDate}&FromDate={fromDate}&clienttype=html&cqid=105&filetype=PDF";
configMongo.Companies_products_commerce_settings_documentsConfig_documents_invoiceByProjectByDateUrl = "KT102_0_0_0={customerCode}&KT107_0_0_0={projectCode}&ToDate={toDate}&FromDate={fromDate}&clienttype=html&cqid=105&filetype=PDF";
configMongo.Companies_products_commerce_settings_documentsConfig_documents_checkUrl = "KT102_0_0_0={customerCode}&KT117_0_0_0={checkNumber}&doctypeid=109&clienttype=html&filetype=PDF";
configMongo.Companies_products_commerce_settings_documentsConfig_documents_statementsUrl = "KT102_0_0_0={customerCode}&ToDate={toDate}&FromDate={fromDate}&clienttype=html&cqid=104&filetype=PDF";
configMongo.Companies_products_commerce_settings_documentsConfig_documents_eTicketUrl = "KT103_0_0_0={ticketCode}&KT102_0_0_0={customerCode}&doctypeid=101&clienttype=html&filetype=PDF";
configMongo.Companies_products_commerce_settings_documentsConfig_documents_batchWeightsUrl = "KT103_0_0_0={ticketCode}&KT102_0_0_0={customerCode}&doctypeid=116&clienttype=html&filetype=PDF";

configMongo.Companies_products_ticket_code = "ticket";
configMongo.Companies_products_ticket_settings_savePdf = false;
configMongo.Companies_products_ticket_settings_systemType_hauler = false;
configMongo.Companies_products_ticket_settings_systemType_ticket_concrete = false;
configMongo.Companies_products_ticket_settings_systemType_ticket_aggregate = false;
configMongo.Companies_products_ticket_settings_dataEndPoints_MobileTicketService_EndPointAddress = "http://localhost";
configMongo.Companies_products_ticket_settings_dataEndPoints_MobileTicketService_Port = 35245;
configMongo.Companies_products_ticket_settings_dataEndPoints_MobileTicketService_Type = "REST";
configMongo.Companies_products_ticket_settings_dataEndPoints_MobileTicketService_SubType = "Client";
configMongo.Companies_products_ticket_settings_dataEndPoints_MobileTicketService_context = "both";
configMongo.Companies_products_ticket_settings_dataEndPoints_EDXTicketService_EndPointAddress = "http://localhost";
configMongo.Companies_products_ticket_settings_dataEndPoints_EDXTicketService_Port = 35245;
configMongo.Companies_products_ticket_settings_dataEndPoints_EDXTicketService_Type = "REST";
configMongo.Companies_products_ticket_settings_dataEndPoints_EDXTicketService_SubType = "Client";
configMongo.Companies_products_ticket_settings_dataEndPoints_EDXTicketService_context = "none";
configMongo.Companies_products_ticket_settings_company_timeZone_value = "0600";
configMongo.Companies_products_ticket_settings_company_timeZone_operator = "-";
configMongo.Companies_products_ticket_settings_company_timeZone_hours = "06";
configMongo.Companies_products_ticket_settings_company_timeZone_minutes = "00";
configMongo.Companies_products_ticket_settings_company_supportEmail = "";
configMongo.Companies_products_ticket_settings_templates_type = "concrete";
configMongo.Companies_products_ticket_settings_templates_name = "TicketJade-Concrete";
configMongo.Companies_products_ticket_settings_templates_body = "|testbcs2 attached concrete ticket";
configMongo.Companies_products_ticket_settings_templates_subject = "|{{ soldToCustomer.code }} - {{ soldToCustomer.name }} - {{ ticketNumber }}";
configMongo.Companies_products_ticket_settings_templates_fileName = "{{ soldToCustomer.code }}_{{ project.code }}_{{ ticketNumber }}";
configMongo.Companies_products_ticket_settings_templates_formatter = "jade";
configMongo.Companies_products_ticket_settings_templates_type2 = "aggregate";
configMongo.Companies_products_ticket_settings_templates_name2 = "TicketJade-Aggregate";
configMongo.Companies_products_ticket_settings_templates_body2 = "|testbcs2 attached aggregate ticket";
configMongo.Companies_products_ticket_settings_templates_subject2 = "|{{ soldToCustomer.code }} - {{ soldToCustomer.name }} - {{ ticketNumber }}";
configMongo.Companies_products_ticket_settings_templates_fileName2 = "{{ location.plantCode }}_{{ company.code }}_{{ soldToCustomer.code }}_{{ ticketNumber }}";
configMongo.Companies_products_ticket_settings_templates_formatter2 = "jade";

configMongo.Companies_products_bulkticket_code = "MobileticketBulk";
configMongo.Companies_products_bulkticket_settings_savePdf = false;
configMongo.Companies_products_bulkticket_settings_systemType_hauler = false;
configMongo.Companies_products_bulkticket_settings_systemType_bulkticket_concrete = false;
configMongo.Companies_products_bulkticket_settings_systemType_bulkticket_aggregate = false;
configMongo.Companies_products_bulkticket_settings_dataEndPoints_MobileTicketService_EndPointAddress = "http://localhost";
configMongo.Companies_products_bulkticket_settings_dataEndPoints_MobileTicketService_Port = 35245;
configMongo.Companies_products_bulkticket_settings_dataEndPoints_MobileTicketService_Type = "REST";
configMongo.Companies_products_bulkticket_settings_dataEndPoints_MobileTicketService_SubType = "Client";
configMongo.Companies_products_bulkticket_settings_dataEndPoints_MobileTicketService_context = "both";
configMongo.Companies_products_bulkticket_settings_dataEndPoints_EDXTicketService_EndPointAddress = "http://localhost";
configMongo.Companies_products_bulkticket_settings_dataEndPoints_EDXTicketService_Port = 35245;
configMongo.Companies_products_bulkticket_settings_dataEndPoints_EDXTicketService_Type = "REST";
configMongo.Companies_products_bulkticket_settings_dataEndPoints_EDXTicketService_SubType = "Client";
configMongo.Companies_products_bulkticket_settings_dataEndPoints_EDXTicketService_context = "none";
configMongo.Companies_products_bulkticket_settings_company_timeZone_value = "0600";
configMongo.Companies_products_bulkticket_settings_company_timeZone_operator = "-";
configMongo.Companies_products_bulkticket_settings_company_timeZone_hours = "06";
configMongo.Companies_products_bulkticket_settings_company_timeZone_minutes = "00";
configMongo.Companies_products_bulkticket_settings_company_supportEmail = "";
configMongo.Companies_products_bulkticket_settings_templates_type = "concrete";
configMongo.Companies_products_bulkticket_settings_templates_name = "TicketJade-Concrete";
configMongo.Companies_products_bulkticket_settings_templates_body = "|testbcs2 attached concrete ticket";
configMongo.Companies_products_bulkticket_settings_templates_subject = "|{{ soldToCustomer.code }} - {{ soldToCustomer.name }} - {{ ticketNumber }}";
configMongo.Companies_products_bulkticket_settings_templates_fileName = "{{ soldToCustomer.code }}_{{ project.code }}_{{ ticketNumber }}";
configMongo.Companies_products_bulkticket_settings_templates_formatter = "jade";
configMongo.Companies_products_bulkticket_settings_templates_type2 = "aggregate";
configMongo.Companies_products_bulkticket_settings_templates_name2 = "TicketJade-Aggregate";
configMongo.Companies_products_bulkticket_settings_templates_body2 = "|testbcs2 attached aggregate ticket";
configMongo.Companies_products_bulkticket_settings_templates_subject2 = "|{{ soldToCustomer.code }} - {{ soldToCustomer.name }} - {{ ticketNumber }}";
configMongo.Companies_products_bulkticket_settings_templates_fileName2 = "{{ location.plantCode }}_{{ company.code }}_{{ soldToCustomer.code }}_{{ ticketNumber }}";
configMongo.Companies_products_bulkticket_settings_templates_formatter2 = "jade";


configMongo.Companies_products_jobsite_code = "jobsite";
configMongo.Companies_products_jobsite_settings_systemType = "cs";
configMongo.Companies_products_jobsite_settings_documentsConfig = "";
configMongo.Companies_products_jobsite_settings_edxGatewayConfig_ServerAddress = "http://localhost";
configMongo.Companies_products_jobsite_settings_edxGatewayConfig_Port = "35245";
configMongo.Companies_products_jobsite_settings_dataEndPoints_DataService_EndPointAddress = "http://localhost";
configMongo.Companies_products_jobsite_settings_dataEndPoints_DataService_Port = 35245;
configMongo.Companies_products_jobsite_settings_dataEndPoints_DataService_Type = "REST";
configMongo.Companies_products_jobsite_settings_dataEndPoints_DataService_SubType = "Client";
configMongo.Companies_products_jobsite_settings_dataEndPoints_SocketEndPoint_EndPointAddress = "http://localhost";
configMongo.Companies_products_jobsite_settings_dataEndPoints_SocketEndPoint_Port = 35245;
configMongo.Companies_products_jobsite_settings_dataEndPoints_SocketEndPoint_Type = "REST";
configMongo.Companies_products_jobsite_settings_dataEndPoints_SocketEndPoint_SubType = "Server";
configMongo.Companies_products_jobsite_settings_futureOrdersEmail_generateTime = "1400";
configMongo.Companies_products_jobsite_settings_futureOrdersEmail_durationTimePeriod = 3;
configMongo.Companies_products_jobsite_settings_futureOrdersEmail_template = "Future Order";
configMongo.Companies_products_jobsite_settings_notifications_orderRequest_template = "Order Request";
configMongo.Companies_products_jobsite_settings_notifications_orderRequest_template_to_name = "";
configMongo.Companies_products_jobsite_settings_notifications_orderRequest_template_to_value = "";
configMongo.Companies_products_jobsite_settings_notifications_orderCreate_template = "Order Create";
configMongo.Companies_products_jobsite_settings_notifications_ticketCreate_template = "Ticket Create";
configMongo.Companies_products_jobsite_settings_company_timeZone_value = "0600";
configMongo.Companies_products_jobsite_settings_company_timeZone_operator = "-";
configMongo.Companies_products_jobsite_settings_company_timeZone_hours = "06";
configMongo.Companies_products_jobsite_settings_company_timeZone_minutes = "00";
configMongo.Companies_products_jobsite_settings_company_timeZone_name = "US/Central";
configMongo.Companies_products_jobsite_settings_company_timeZone_defaultRegion = "USA";
configMongo.Companies_products_jobsite_settings_user_sms = "";
configMongo.Companies_products_jobsite_settings_user_sales = "";
configMongo.Companies_products_jobsite_settings_user_customer_code = "";
configMongo.Companies_products_jobsite_settings_user_customer_name = "";
configMongo.Companies_products_jobsite_settings_user_timeZone_value = "";
configMongo.Companies_products_jobsite_settings_user_timeZone_operator = "";
configMongo.Companies_products_jobsite_settings_user_timeZone_hours = "";
configMongo.Companies_products_jobsite_settings_user_timeZone_minutes = "";
configMongo.Companies_products_jobsite_settings_user_permissions_batchWeights = false;
configMongo.Companies_products_jobsite_settings_user_permissions_truckTimes = true;
configMongo.Companies_products_jobsite_settings_user_permissions_pricing = false;
configMongo.Companies_products_jobsite_settings_user_permissions_mapping = true;
configMongo.Companies_products_jobsite_settings_user_permissions_futureOrderEmail = false;
configMongo.Companies_products_jobsite_settings_user_permissions_changeCustomer = false;
configMongo.Companies_products_jobsite_settings_user_permissions_timeZone = false;

configMongo.Companies_products_supply_code = "supply";
configMongo.Companies_products_supply_settings_user_vendor = "";
configMongo.Companies_products_supply_settings_user_permissions_configure = false;
configMongo.Companies_products_supply_settings_user_permissions_plan = false;
configMongo.Companies_products_supply_settings_user_permissions_alias = false;
configMongo.Companies_products_supply_settings_user_locations = "";
configMongo.Companies_products_supply_settings_dataEndPoints_MasterData_EndPointAddress = "http://localhost";
configMongo.Companies_products_supply_settings_dataEndPoints_MasterData_Port = 35245;
configMongo.Companies_products_supply_settings_dataEndPoints_MasterData_Type = "REST";
configMongo.Companies_products_supply_settings_dataEndPoints_MasterData_SubType = "Client";
configMongo.Companies_products_supply_settings_dataEndPoints_SocketEndPoint_EndPointAddress = "127.0.0.1";
configMongo.Companies_products_supply_settings_dataEndPoints_SocketEndPoint_Port = 35245;
configMongo.Companies_products_supply_settings_dataEndPoints_SocketEndPoint_Type = "REST";
configMongo.Companies_products_supply_settings_dataEndPoints_SocketEndPoint_SubType = "Server";

configMongo.Companies_products_evoadmin_code = "evoadmin";
configMongo.Companies_products_evoadmin_settings = "";

module.exports = configMongo;